package ngodanghieu.doan.entities;
// Generated Apr 12, 2020 7:04:55 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Favorite generated by hbm2java
 */
@Entity
@Table(name = "favorite", catalog = "ngodanghieu")
public class Favorite implements java.io.Serializable {

	private Integer favoriteId;
	private Long userId;
	private Long homeId;

	public Favorite() {
	}

	public Favorite(Long userId, Long homeId) {
		this.userId = userId;
		this.homeId = homeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "favorite_id", unique = true, nullable = false)
	public Integer getFavoriteId() {
		return this.favoriteId;
	}

	public void setFavoriteId(Integer favoriteId) {
		this.favoriteId = favoriteId;
	}

	@Column(name = "user_id", nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "home_id", nullable = false)
	public Long getHomeId() {
		return this.homeId;
	}

	public void setHomeId(Long homeId) {
		this.homeId = homeId;
	}

}
