package ngodanghieu.doan.entities;
// Generated Apr 12, 2020 7:04:55 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ratings generated by hbm2java
 */
@Entity
@Table(name = "ratings", catalog = "ngodanghieu")
public class Ratings implements java.io.Serializable {

	private Integer id;
	private int stars;
	private int userId;
	private int homeId;

	public Ratings() {
	}

	public Ratings(int stars, int userId, int homeId) {
		this.stars = stars;
		this.userId = userId;
		this.homeId = homeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "stars", nullable = false)
	public int getStars() {
		return this.stars;
	}

	public void setStars(int stars) {
		this.stars = stars;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "home_id", nullable = false)
	public int getHomeId() {
		return this.homeId;
	}

	public void setHomeId(int homeId) {
		this.homeId = homeId;
	}

}
