package ngodanghieu.doan.entities;
// Generated Jan 4, 2020 11:14:33 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UserFcm generated by hbm2java
 */
@Entity
@Table(name = "user_fcm", catalog = "ngodanghieu")
public class UserFcm implements java.io.Serializable {

	private Long userFcmId;
	private User user;
	private String deviceId;
	private String token;
	private Date createdDate;
	private Date modifiedBy;

	public UserFcm() {
	}

	public UserFcm(User user, String deviceId, String token, Date createdDate, Date modifiedBy) {
		this.user = user;
		this.deviceId = deviceId;
		this.token = token;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_fcm_id", unique = true, nullable = false)
	public Long getUserFcmId() {
		return this.userFcmId;
	}

	public void setUserFcmId(Long userFcmId) {
		this.userFcmId = userFcmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "device_id", nullable = false, length = 65535)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "token", nullable = false, length = 65535)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_by", nullable = false, length = 10)
	public Date getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Date modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
